### PR TITLE
Don't handle VIEW and DIAL intents.

### PR DESCRIPTION
**Pull request by hugomg**
Don't handle VIEW and DIAL intents, as proposed in #31.

This PR also broadens the intent filter to accept any `text/*` MIME type.

### CODE REVIEW

**Comment by hugomg** [comment]
I understand that getting rid of features is always a bit controversial but I think it is a good idea here. That said, if the final decision is to leave things as is then we can cherry pick just the less controversial changes.

**Comment by tasn** [comment]
My only last doubt about removing VIEW/DIAL intents is that with them you can have both use-cases, and without them, you can't have share to clipboard set if you want it. I wonder how many people actually set share to clipboard to "open always" by mistake with the notification off.

Also, why did you change the intent to `text/**` if you reject it later on? This feels like a bad user experience, having the option to choose share to clipboard only to get an error message.

**Comment by hugomg** [comment]
> why did you change the intent to text/** if you reject it later on? 

Other `text/*` MIME types such as `text/html` and `text/rtf` are supposed to be accepted. The code to handle those cases was already present in ShareToClipboardActivity but for some reason the old android manifest only listed text/plain and text/x-vcard.

> My only last doubt about removing VIEW/DIAL intents is that with them you can have both use-cases, 

I am not sure if making it slightly easier to copy an email address outweighs the problems related to having Share to Clipboard appear outside of a "share" context.

> I wonder how many people actually set share to clipboard to "open always" by mistake with the notification off.

Accidentally setting Share to Clipboard as the default probably isn't common but if it does happen then it is very confusing (because the VIEW intent isn't viewing anything) and also difficult to undo. Given that it is still possible to copy phone numbers and email addresses without Share to Clipboard's help, I am not sure if handling those VIEW intents is worth the hassle. That said, if we do end up choosing to keep the view intents then I think we should consider ways to mitigate those problems, such as making sure that Share to Clipboard always gives some visual feedback when it activates.

**Comment by hugomg** [comment]
I don't know how to test if other text/* MIME types are really working because I don't know any apps that share those. I assumed that the current code is doing the right thing.

**Comment by tasn** [comment]
> > why did you change the intent to text/** if you reject it later on?
> 
> Other `text/*` MIME types such as text/html and text/rtf are supposed to be accepted. The code to handle those cases was already present in ShareToClipboardActivity but for some reason the old android manifest only listed text/plain and text/x-vcard.

This is what confused me:
`handleSendText(intent, R.string.error_type_not_supported);`
This error string being different to the `text/plain` counterpart... 

> I am not sure if making it easier to copy an email address outweighs the problems that can happen when Share to Clipboard appears outside of a "share" context.

I'm not 100% convinced anymore.

> 
> Accidentally setting Share to Clipboard as the default probably isn't common but if it does happen then it is very confusing (because the VIEW intent isn't viewing anything) and also difficult to undo. Given that it is still possible to copy phone numbers and email addresses without Share to Clipboard's help, I am not sure if handling those VIEW intents is worth the hassle. That said, if we do end up choosing to keep the view intents then I think we should consider ways to mitigate those problems, such as making sure that Share to Clipboard always gives some visual feedback when it activates.

I think we used to have a toast, though we probably got rid of it when we moved to the notification. Maybe we should show a toast if the notification is not enabled?

**Comment by tasn** [comment]
> I don't know how to test if other text/* MIME types are really working because I don't know any apps that share those. I assumed that the existing implementation of handleSendText is doing the right thing.

Yeah, sounds reasonable.

**Comment by hugomg** [comment]
> This error string being different to the text/plain counterpart...

That part was already like that before. I guess it is supposed to give a reasonable error message in case if Intent.EXTRA_TEXT is missing. I don't know of a concrete example of when that might happen.

> Maybe we should show a toast if the notification is not enabled?

I agree that it would be nice to give some sort of feedback when the notification is not present. I'll open another issue for it.

**Comment by hugomg** [comment]
By the way, do we have a final verdict on the VIEW and DIAL intents? Do we keep them or do we take them out?

**Comment by tasn** [comment]
Let's get rid of it, fine. So let me know when the PR is ready.

**Comment by hugomg** [comment]
I think it is good to go. :) I'd rather implement the toast in a separate PR.

**Pull request merged**
