### PR TITLE
Added Basque and Spanish metadata, tiny corrections on strings and improved Readme

### PR DESCRIPTION
**Pull request by Porrumentzio**
I didn't add new screenshots, but I propose you to add some of the use on Share menu, some with the notification and some about the in-app settings.
This way it would be more attractive (and it will appear more on F-Droid, as they give preference to content with metadata)

### CODE REVIEW

**Comment by Porrumentzio** [comment]
I now added an explanation about translating metadata, on the `Contributing` part on the README.

**Comment by tasn** [comment]
README: awesome!
Could you please get rid of the merge commit and instead rebase on top of master? We try to maintain a linear history in this repo.

Thanks!

**Comment by Porrumentzio** [comment]
I don't know much about git, so I had to read this explanation: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

I'll try to rebase it and after, PR.
Wish me luck haha

**Comment by tasn** [comment]
Haha, git is an important tool to any developer, learning how to use it better will surely save you time in the long run!

**Comment by Porrumentzio** [comment]
Yes, I know. Although, the main thing is that I'm not a developer, but a simple translator :)
But yes, I'm learning git little by little

**Comment by tasn** [comment]
So let's not waste your time! It's not your fault we don't have a proper translation system set up. :|

**Comment by Porrumentzio** [comment]
Nah, the translation are so tiny to build a system (Weblate, Crowdin...). And all was okay with the translation. The thing is that I don't know git enough to make rebases and so, but it's easy with a simple merge commit

**Pull request closed without merging**
