### PR TITLE
[Rebased] Added Basque and Spanish metadata and improved Readme

### PR DESCRIPTION
**Pull request by Porrumentzio**
I think I did it as I should, but my local git was up to date with master, so no change.
Here is it, which I suppose is the same as the previous PR.

### CODE REVIEW

**Comment by tasn** [comment]
I'm still getting "This branch cannot be rebased due to conflicts". It's probably because you have a merge commit. Sec, I'll fix the PR myself. :)

**Comment by tasn** [comment]
Actually, easier if you do it, as I don't know which translation is correct, if you can't manage, we can just do it together.
What you need to do is run:
```
git rebase 20b249242407863b7edb614fdc386bd9d3784451
```
After that it will tell you rebase failed, and will tell you there are conflicting files. You will need to edit these files and search for "<<<<" and then remove these markers (there are 3 for each change) and only leave the correct version, so for example:
```
<<<<<<< HEAD
		\n\n\nIturburu erabat irekikoa, iturburu-kodea hemen eskuragarri dagolarik:
=======
		\n\n\nIturburu erabat irekiko, iturburu-kodea hemen eskuragarri dagolarik:
>>>>>>> 59cff73... Added Basque (eu) translation
```
Would need to change to (assuming I chose the correct translation):
```
		\n\n\nIturburu erabat irekiko, iturburu-kodea hemen eskuragarri dagolarik:
``
After that you need to run `git add -u` and then `git rebase --continue`. After all is done, you can: `git push --force origin` to update this pull request.

**Comment by Porrumentzio** [comment]
Thanks for the explanations! Try it now

**Comment by tasn** [comment]
You're fast! Thanks a lot!

**Comment by tasn** [comment]
Hm... btw, ready for release or is there anything else you'd like to address before? I remember I need to take new screenshots before the release.
Btw, maybe we also need a changelog for this upcoming release:

```
* Translation: update Basque translation on f-droid
```

**Comment by Porrumentzio** [comment]
Haha, the email notifications are fast to :)
Is now good?

**Comment by tasn** [comment]
No, I'm talking about version 28! Because if we want it to show on f-droid I need to release a new version. :)

Btw, I can't unfortunately take new screenshots either because my share-to is also full of other things. :|
It's a bit annoying with the old icon though...

**Comment by Porrumentzio** [comment]
Perfect about 28. Did you update your github repo? I'll update my fork if so.

About the screenshots I'll try again. These are the possible ones (ignore the language, I would change it):

On my old Stock ROM Android
irudia

On my new /e/OS Android
irudia

**Comment by tasn** [comment]
The one from stock Android is better!
Repo: pushed, thanks!

**Comment by Porrumentzio** [comment]
I'm doing it:

irudia
irudia
irudia
irudia

**Comment by Porrumentzio** [comment]
Btw, which Changelog I have to translate? Those on metadata or `ChangeLog.md`?

**Comment by tasn** [comment]
What's exodus privacy? I'd rather not promote a 3rd party like this...

What to translate: just the `fastlane/` ones, the Changelog.md is for devs and I may drop it at some point.

**Comment by Porrumentzio** [comment]
Exodus Privacy is a tracker analyzer, well known: https://exodus-privacy.eu.org/en/page/what/

I will take other screenshots if necessary

**Comment by tasn** [comment]
preferably yeah, I'm not comfortable promoting a 3rd party. Please stick to Wikipedia/EteSync. :)

**Comment by Porrumentzio** [comment]
Done. Wikipedia.org with "Clipboard" entry.

**Comment by tasn** [comment]
Sweet. :)

**Comment by Porrumentzio** [comment]
I'll PR the new changes on other thread

**Comment by tasn** [comment]
Great! @talhacohen (@talhaco ?) is working on a new improvement so may have a new release soon (so more changelog entries). :)

**Comment by Porrumentzio** [comment]
Perfect. If you could, inform me when added new changelogs

**Comment by tasn** [comment]
Will do.

**Pull request merged**
