### PR TITLE
Some improvements to the vCard code

### LINKED ISSUE #27: Update ez-vcard dependency
The latest version of [ez-vcard](https://github.com/mangstadt/ez-vcard) is 0.10.6. We should also check if some of the latest updates would let us improve our code a little bit.

### PR DESCRIPTION
**Pull request by hugomg**
* Update ez-vcard dependency (Fixes #27)
* Use ez-vcard's streaming parser

We might want to wait until #29 is clarified to ensure that these changes really aren't breaking anything.

### CODE REVIEW

**Comment by tasn** [comment]
He already replied to #29.

Let me know whenever you would like me to review this PR.

**Comment by tasn** [comment]
Should I now release a new version, or do you have any other pending PRs?

**Comment by hugomg** [comment]
I think I'm done for now ;)

That said, if you ever change your mind about the "open emails with this app" thing then I can make a PR for that too.

**Comment by tasn** [comment]
Great! I replied there and I'm happy with a PR for that, so I'll wait until that's in before making a release.

Thanks again for all of your work, and I added you to the contributors list in the readme, which I previously forgot to do.

**Pull request merged**
