### PR TITLE
Added new screenshots and translated changelogs for Basque and Spanish

### PR DESCRIPTION
**Pull request by Porrumentzio**
I did it with rebase. I hope well.

I changed *f-droid* to *F-Droid* on en-US changelog too, so there is conflict.

### CODE REVIEW

**Comment by tasn** [comment]
Look at the list of changes your have in this PR, you have my commits too for some reason. You should probably rebase over my changes before even making changes to make sure you are up to date.

**Comment by Porrumentzio** [comment]
I [updated the fork](https://gist.github.com/CristinaSolana/1885435) before changing anything and git also says that all is up to date, so I think all is well.

**Comment by tasn** [comment]
Look here in the web ui, it isn't. I think you didn't update the fork correctly, because as you can see, it's also showing my commits. I'll fix it for you, one sec.

**Comment by tasn** [comment]
You for some reason edited 28.txt too, sec fixing that too.

**Comment by Porrumentzio** [comment]
Yes, I said that before:

> I changed f-droid to F-Droid on en-US changelog too, so there is conflict.

**Comment by tasn** [comment]
Anything else missing, or should I make a release? Great job!

**Comment by Porrumentzio** [comment]
Do it! I somewhen add the Esperanto translation, but not by now. Thanks, a pleasure!

**Comment by tasn** [comment]
Wow, how many languages do you speak??

**Comment by tasn** [comment]
Released

**Comment by Porrumentzio** [comment]
Hahah, I speak Basque, Spanish, English, Esperanto and Catalan. I also understand Galician and I'm going to learn arabic!

**Comment by tasn** [comment]
Very cool!

**Pull request merged**
