### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hugomg**
The thing I am not 100% sure about here is the androidx.legacy dependency. Do you remember why it was originally put there? Nothing seemed to break when I removed it but at the same time I couldn't find any documentation on the internet to clarify what it was supposed to be doing in the first place.

### CODE REVIEW

**Comment by tasn** [comment]
It was added in bac353b66f052105a2a1e4e156b8cc84c3715c31 and I'm pretty sure it was actually needed. I'd say: keep it for now, don't remove it. At least until we have the time to properly test the app without it.

Once you remove it I'll merge the app and make a new release.

Thanks!

**Comment by tasn** [comment]
Do you have another PR on the way, or should I take a look into making a release?

**Comment by hugomg** [comment]
I'll be creating another PR soon with the linter stuff. I'm still working on it.

**Comment by tasn** [comment]
No rush, was just wondering. :)

**Pull request merged**
