### PR TITLE
Show a toast if there is no notification

### LINKED ISSUE #33: Should we give some visual feedback if notifications are disabled?
It would be nice if we always gave some visual feedback after copying something, even if notifications are disabled.

In versions of AOSP that come with a built-in "share to clipboard" feature, there is a toast to provide that visual feedback. This is also what this app used to do before commit [bac353b6](https://github.com/tengusw/share_to_clipboard/commit/bac353b66f052105a2a1e4e156b8cc84c3715c31), which introduced the re-sharing notification.

### PR DESCRIPTION
**Pull request by hugomg**
This ensures that there is always visual feedback when using share to
clipboard. Fixes #33.

### CODE REVIEW

**Comment by tasn** [comment]
Great, thanks! Should I make a release now? Or do you have any other changes in the pipeline?

**Comment by hugomg** [comment]
I think we can make a release now :)

**Comment by tasn** [comment]
Done.

**Comment by hugomg** [comment]
My pleasure :)

**Pull request merged**
