### PR TITLE
Added Basque (eu) translation

### PR DESCRIPTION
**Pull request by Porrumentzio**

### CODE REVIEW

**Comment by tasn** [comment]
Merged, thanks a lot! Will release a new version in a moment.

**Comment by Porrumentzio** [comment]
Will also the version on F-Droid be updated?

**Comment by tasn** [comment]
Yeah, it just takes time as f-droid build it rather than me. Please check with me in a few days if f-droid still haven't build anything.

**Comment by Porrumentzio** [comment]
Hi! F-Droid published the new version with the app in Basque but the metadata (name, description...) on F-Droid remains the same.
Does this have to be this way? Or is an error?

**Comment by tasn** [comment]
Ah damn, that's right. You also need to translate the strings under the `fastlane' directory. There's one example there (`he_IL`), see how it's done.

Sorry, I completely forgot about f-droid.

**Comment by Porrumentzio** [comment]
Okay. How about if I add some new screenshots to the english metadata?

And should I add all the .txt metadata of `en-US`?
irudia

Or just `shor_description.txt` and `title.txt` on `/eu` directory?

**Comment by tasn** [comment]
What's the `eu` directory? You just need title and the two descriptions. No need to add screenshots in Basque, I think it's a bit of an overkill.

**Comment by Porrumentzio** [comment]
> What's the eu directory?

I created `~/fastlane/metadata/android/eu` directory to add there the basque metadata. Shouldn't I?

> No need to add screenshots in Basque

I didn't say about add other screenshots to Basque metadata, but to general, as in the current screenshots, even the logo of the app is another.

**Comment by tasn** [comment]
Ah, I didn't realise this was the country code for Basque.

Screenshots: good idea, new screenshots welcome, though please try to make the content in the image neutral if possible, maybe something similar to what's already there.

**Comment by Porrumentzio** [comment]
Perfect, will that be good on Basque language or better on English?
I'll use, as it's there, your Wikipedia of the day app as example

**Comment by tasn** [comment]
In English please, yeah, so it'll be more accessible to others. Sure, using wiki of the day would be great if possible, though not the end of the world if something else.

**Comment by Porrumentzio** [comment]
Shall I use EteSync from F-Droid? I don't find any other app made by you on there.

(Also I'll translate changelogs into basque and create all the spanish metadata too)

**Comment by tasn** [comment]
Haha, EteSync would be great. :heart_eyes: 
You should use EteSync btw, it's great and version 2.0 is coming out soon! :)

Great, thanks a lot for all of your great work!

**Comment by Porrumentzio** [comment]
Hi! I did the metadata but I think I won't be able to create appropriate screenshots as I have a lot of apps on the Share menu, so Share to clipboard is almost invisible. 

I'll PR the new metadata and you could add appropriate screenshots, sorry.

*About EteSync, is it possible to use it with Nextcloud accounts?*

**Comment by tasn** [comment]
Nextcloud accounts: no. The reason for that is that nextcloud doesn't encrypt your data and also because of how it works, can't.
That's why EteSync was created, because it couldn't be done with existing applications.

**Comment by Porrumentzio** [comment]
That's interesting! Is EteSync self-hostable?

**Comment by tasn** [comment]
It is! https://github.com/etesync/server
Though it's end-to-end encrypted so unlike e.g. NextCloud your data is safe even if you don't host it locally!

**Comment by Porrumentzio** [comment]
Yes, that's logic. Thanks Tengu!

**Pull request merged**
